### ISSUE TITLE
[Bug] vLLM server crashes upon assertions instead of throwing errors to client (e.g. fails when requests with different temperatures are sent)

### ISSUE THREAD

**Issue by cglagovichTT** [tenstorrent/vllm#29]
### Anything you want to discuss about vllm.

You can repro by starting up the server example and sending requests with different temperatures. Failure should look like
```  File "/home/cglagovich/vllm/vllm/entrypoints/openai/serving_completion.py", line 201, in create_completion
    async for i, res in result_generator:
  File "/home/cglagovich/vllm/vllm/utils.py", line 506, in merge_async_iterators
    item = await d
  File "/home/cglagovich/vllm/vllm/engine/multiprocessing/client.py", line 598, in _process_request
    raise request_output
  File "/home/cglagovich/vllm/vllm/engine/multiprocessing/client.py", line 598, in _process_request
    raise request_output
AssertionError: Currently only supporting same temperature for all sequences in batch```

**Comment by skhorasganiTT** [comment]
Also reported in #39

**Comment by cglagovichTT** [comment]
Is #39 really a duplicate of this?

**Comment by skhorasganiTT** [comment]
Addressed invalid request parameters in https://github.com/tenstorrent/vllm/pull/41, so that invalid request errors are returned instead of the server crashing. For the case of different top-pk parameters in the same batch, the same solution cannot be applied since any error or assertion during step execution will crash the server, so it was changed to a warning instead. Created a separate issue for adding support for different top-pk parameters in the same batch: https://github.com/tenstorrent/vllm/issues/42
